#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime
# environment changes to make the snap work here.  You may also insert
# security confinement/deprecation/obsoletion notice of the snap here.

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

# HACK: Program assumes model files under PWD...
if test $# -lt 2; then
    waifu2x
else
    declare input_file="${1}"; shift
    declare output_file="${1}"; shift

    declare \
        input_file_absolute_path \
        output_file_absolute_path

    input_file_absolute_path="$(realpath "${input_file}")"
    output_file_absolute_path="$(realpath "${output_file}")"
    unset \
        input_file \
        output_file

    cd "${SNAP}"/bin
    ./waifu2x "${input_file_absolute_path}" "${output_file_absolute_path}" "${@}"
fi
